This is makeindex, version 2.15 [TeX Live 2015] (kpathsea + Thai support).
Scanning style file ./race.ist.............................done (29 attributes redefined, 0 ignored).
Scanning input file race.acn....done (377 entries accepted, 0 rejected).
Sorting entries......done (4176 comparisons).
Generating output file race.acr....done (105 lines written, 0 warnings).
Output written in race.acr.
Transcript written in race.alg.
